server {
    listen 80;
    listen [::]:80;
    server_name expertakpp.ru www.expertakpp.ru cms.expertakpp.ru;

    return 301 https://$host$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name *.expertakpp.ru;

    client_max_body_size 25m;

    include /etc/nginx/snippets/akpp-web-locations.conf;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name expertakpp.ru www.expertakpp.ru *.expertakpp.ru;

    ssl_certificate /etc/letsencrypt/live/expertakpp.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/expertakpp.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 25m;

    include /etc/nginx/snippets/akpp-web-locations.conf;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name cms.expertakpp.ru;

    ssl_certificate /etc/letsencrypt/live/expertakpp.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/expertakpp.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 100m;

    include /etc/nginx/snippets/akpp-cms-locations.conf;
}
