location ~* ^/_ipx/[^/]+/(images/.+)$ {
    proxy_cache akpp_ipx_cache;
    proxy_cache_key $akpp_ipx_cache_key;
    proxy_cache_methods GET HEAD;

    proxy_cache_valid 200 7d;
    proxy_cache_valid 404 1m;

    proxy_cache_lock on;
    proxy_cache_lock_timeout 120s;

    proxy_cache_use_stale updating error timeout http_500 http_502 http_503 http_504;
    proxy_cache_background_update on;

    add_header X-Cache-Status $upstream_cache_status always;
    add_header Vary Accept always;

    include /etc/nginx/snippets/akpp-proxy-common.conf;
    proxy_pass http://127.0.0.1:3000/$1;
}

location ^~ /_ipx/ {
    proxy_cache akpp_ipx_cache;
    proxy_cache_key $akpp_ipx_cache_key;
    proxy_cache_methods GET HEAD;

    proxy_cache_valid 200 7d;
    proxy_cache_valid 404 1m;

    proxy_cache_lock on;
    proxy_cache_lock_timeout 120s;

    proxy_cache_use_stale updating error timeout http_500 http_502 http_503 http_504;
    proxy_cache_background_update on;

    add_header X-Cache-Status $upstream_cache_status always;
    add_header Vary Accept always;

    include /etc/nginx/snippets/akpp-proxy-common.conf;
    proxy_pass http://127.0.0.1:3000;
}

location / {
    include /etc/nginx/snippets/akpp-proxy-common.conf;
    proxy_pass http://127.0.0.1:3000;
}
