proxy_connect_timeout 5s;
proxy_send_timeout 60s;
proxy_read_timeout 60s;
send_timeout 60s;
proxy_cache_lock on;

proxy_cache_path /var/cache/nginx/akpp_ipx
  levels=1:2
  keys_zone=akpp_ipx_cache:50m
  max_size=10g
  inactive=7d
  use_temp_path=off;

map $request_uri $akpp_ipx_is_auto_format {
  default 0;
  ~^/_ipx/f_auto(?:&|$) 1;
}

map $akpp_ipx_is_auto_format$http_accept $akpp_ipx_accept_variant {
  default '';
  ~^1.*image/avif avif;
  ~^1.*image/webp webp;
  ~^1.* image;
}

map $scheme$request_method$host$request_uri$akpp_ipx_accept_variant $akpp_ipx_cache_key {
  default $scheme$request_method$host$request_uri$akpp_ipx_accept_variant;
}

proxy_cache_path /var/cache/nginx/akpp_assets
  levels=1:2
  keys_zone=akpp_assets_cache:100m
  max_size=20g
  inactive=30d
  use_temp_path=off;
