FROM node:20-alpine AS builder

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@10.29.3 --activate

ARG NUXT_PUBLIC_DIRECTUS_PUBLIC_URL
ENV NUXT_PUBLIC_DIRECTUS_PUBLIC_URL=$NUXT_PUBLIC_DIRECTUS_PUBLIC_URL
ARG NUXT_DIRECTUS_CACHE_TTL_SECONDS
ENV NUXT_DIRECTUS_CACHE_TTL_SECONDS=$NUXT_DIRECTUS_CACHE_TTL_SECONDS
ARG NITRO_REDIS_HOST
ENV NITRO_REDIS_HOST=$NITRO_REDIS_HOST
ARG NITRO_REDIS_PORT
ENV NITRO_REDIS_PORT=$NITRO_REDIS_PORT
ARG NITRO_REDIS_DB
ENV NITRO_REDIS_DB=$NITRO_REDIS_DB
ARG NITRO_REDIS_PASSWORD
ENV NITRO_REDIS_PASSWORD=$NITRO_REDIS_PASSWORD
ARG NITRO_API_CACHE_TTL_SECONDS
ENV NITRO_API_CACHE_TTL_SECONDS=$NITRO_API_CACHE_TTL_SECONDS
ARG NITRO_SSR_SWR_SECONDS
ENV NITRO_SSR_SWR_SECONDS=$NITRO_SSR_SWR_SECONDS
ARG NUXT_CACHE_PURGE_TOKEN
ENV NUXT_CACHE_PURGE_TOKEN=$NUXT_CACHE_PURGE_TOKEN

COPY . .

WORKDIR /app/apps/web

ENV NODE_ENV=production

RUN pnpm install --frozen-lockfile --force
RUN pnpm build

# -------- runtime stage --------
FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/apps/web/.output ./.output
COPY --from=builder /app/apps/web/package.json ./package.json

ENV NODE_ENV=production
ENV NITRO_HOST=0.0.0.0
ENV NITRO_PORT=3000

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
